Cargo.lock, Cargo.toml, src/app_config.rs, src/issues/github.rs, src/issues/jira.rs, src/issues/mod.rs, src/main.rs, src/state.rs, src/step.rs, src/workflow.rs
See #68 for more detail on motivation and results. Tested GitHub issue functionality by verifying issues are listed for this repo. Tested Jira list issue functionality on inventory-server. I suppose we should also test Jira transitions to make sure I didn't break that.
=> refactor: Remove async code and Octocrab to make Dobby lighter (closes #68)

docs/src/config/step/UpdateProjectFromCommits.md, src/conventional_commits.rs, src/lib.rs, src/main.rs, src/semver.rs, src/step.rs, tests/dobby.toml, tests/prerelease.rs
=> feat: Support pre-releases in `UpdateProjectFromCommits`.

Makefile.toml, dobby.toml, docs/src/config/step/PrepareRelease.md, src/command.rs, src/git.rs, src/issues/mod.rs, src/lib.rs, src/releases/changelog.rs, src/releases/conventional_commits.rs, src/releases/github.rs, src/releases/mod.rs, src/releases/semver.rs, src/state.rs, src/step.rs, tests/dobby.toml, tests/git_repo_helpers/mod.rs, tests/prepare_release_dry_run.rs, tests/prerelease.rs, tests/prerelease_after_normal_release.rs
=> feat: Add a `dry-run` option to the `PrepareRelease` step.

docs/src/config/packages.md, src/command.rs, src/config.rs, src/releases/conventional_commits.rs, src/releases/mod.rs, src/releases/package.rs, src/releases/semver.rs, src/state.rs, src/step.rs, tests/prepare_release_package_selection/Cargo_different_version.toml, tests/prepare_release_package_selection/invalid_versioned_file_format_knope_dry_run_output.txt, tests/prepare_release_package_selection/multiple_files_in_package_dry_run_output.txt, tests/prepare_release_package_selection/multiple_files_in_package_output.txt, tests/prepare_release_package_selection/multiple_packages_dry_run_output.txt, tests/prepare_release_package_selection/test_prepare_release_multiple_files_inconsistent_versions.txt, tests/snapshot_tests.rs
=> feat: Support multiple versioned_files in one package.

Cargo.lock, src/git.rs, src/releases/git.rs, tests/prepare_release.rs
=> fix: Tags were being processed backwards starting in 0.4.0

src/releases/cargo.rs, src/releases/package.rs, src/releases/package_json.rs, src/releases/pyproject.rs, src/step.rs, tests/prepare_release.rs, tests/prepare_release/package_selection/Cargo.toml_knope.toml_INVALID_output.txt, tests/prepare_release/package_selection/Cargo.toml_knope.toml_MISSING_output.txt, tests/prepare_release/package_selection/go.mod_knope.toml_INVALID_output.txt, tests/prepare_release/package_selection/go.mod_knope.toml_MISSING_output.txt, tests/prepare_release/package_selection/multiple_files_in_package_knope.toml_INVALID_output.txt, tests/prepare_release/package_selection/multiple_files_in_package_knope.toml_MISSING_output.txt, tests/prepare_release/package_selection/package.json_knope.toml_INVALID_output.txt, tests/prepare_release/package_selection/package.json_knope.toml_MISSING_output.txt, tests/prepare_release/package_selection/pyproject.toml_knope.toml_INVALID_output.txt, tests/prepare_release/package_selection/pyproject.toml_knope.toml_MISSING_output.txt
=> fix: Include file paths in file-related errors.

src/releases/conventional_commits.rs, src/releases/package.rs, tests/prepare_release.rs, tests/prepare_release/package_selection/NEW_CHANGELOG.md
=> feat: `PrepareRelease` will create a `changelog` file if it was missing.

src/releases/git.rs
=> fix: Always set a committer on tags to resolve compatibility issue with GitLab.

docs/src/config/packages.md, src/releases/package.rs, src/releases/pyproject.rs, src/step.rs, tests/prepare_release.rs, tests/prepare_release/package_selection/multiple_files_in_package_knope.toml_INVALID_output.txt, tests/prepare_release/package_selection/pyproject.toml_knope.toml_INVALID_output.txt, tests/prepare_release/pyproject_toml/dry_run_output.txt, tests/prepare_release/pyproject_toml/expected_mixed_pyproject.toml.toml, tests/prepare_release/pyproject_toml/expected_pep621_pyproject.toml.toml, tests/prepare_release/pyproject_toml/expected_poetry_pyproject.toml.toml, tests/prepare_release/pyproject_toml/knope.toml, tests/prepare_release/pyproject_toml/mixed_pyproject.toml, tests/prepare_release/pyproject_toml/pep621_pyproject.toml, tests/prepare_release/pyproject_toml/poetry_pyproject.toml
=> feat: Support PEP621 in `pyproject.toml`.

src/releases/git.rs
Resolves #322.
This was tested locally on a repo that was seeing issues with the latest `0.9` being preferred over `0.1x`, and it works. I did not write a proper test because I'm not sure how to integrate it into the current testing setup. Let me know if you'd like me to try to do that.
=> fix: determining latest versions from tags

src/app_config.rs, src/command.rs, src/config.rs, src/git.rs, src/lib.rs, src/releases/go.rs, src/releases/mod.rs, src/releases/package.rs, src/releases/semver/version.rs, src/step.rs
Because error messages should be readable.
=> feat: Remove any potential panics

src/git.rs, tests/git_repo_helpers/mod.rs, tests/prepare_release.rs, tests/prepare_release/merge_commits/CHANGELOG.md, tests/prepare_release/merge_commits/Cargo.toml, tests/prepare_release/merge_commits/EXPECTED_CHANGELOG.md, tests/prepare_release/merge_commits/EXPECTED_Cargo.toml, tests/prepare_release/merge_commits/dry_run_output.txt, tests/prepare_release/merge_commits/knope.toml
FYI @erichulburd this is what you found in #435
=> fix: Handle merge commits in history. Thanks @erichulburd!

docs/package-lock.json, docs/package.json
=> Revert "chore(deps): update dependency astro-expressive-code to ^0.27.0"

docs/src/content/docs/reference/default-workflows.md, docs/src/content/docs/tutorials/releasing-basic-projects.mdx, docs/src/content/docs/tutorials/releasing-multiple-packages.mdx, src/config/mod.rs, tests/generate/github/knope.toml
=> fix: Add `[github]` section with `knope --generate`

.changeset/add_ignore_go_major_versioning_option.md, docs/src/content/docs/recipes/multiple-major-go-versions.md, docs/src/content/docs/reference/Config File/packages.md, src/config/toml/package.rs, src/step/releases/go.rs, src/step/releases/package.rs, src/step/releases/semver/mod.rs, src/step/releases/versioned_file.rs, tests/prepare_release/go_modules/ignore_go_major_versioning/dry_run_output.txt, tests/prepare_release/go_modules/ignore_go_major_versioning/expected/go.mod, tests/prepare_release/go_modules/ignore_go_major_versioning/expected/knope.toml, tests/prepare_release/go_modules/ignore_go_major_versioning/source/go.mod, tests/prepare_release/go_modules/ignore_go_major_versioning/source/knope.toml, tests/prepare_release_go_modules.rs
=> Allow turning off go.mod major version features

docs/src/content/docs/recipes/customizing-changelogs.md
=> docs: Fix some broken links

.changeset/move_headerlevel_to_internal_parse_with_changelognew.md, Cargo.lock, Cargo.toml, crates/knope-versioning/CHANGELOG.md, crates/knope-versioning/Cargo.toml
This PR was created by Knope. Merging it will create a new release
=> chore: prepare releases

.changeset/move_headerlevel_to_internal_parse_with_changelognew.md, Cargo.lock, Cargo.toml, crates/knope-versioning/CHANGELOG.md, crates/knope-versioning/Cargo.toml
=> Revert "chore: prepare releases"

.changeset/add_pomxml_support.md, Cargo.lock, Cargo.toml, crates/knope-versioning/Cargo.toml, crates/knope-versioning/src/versioned_file/maven_pom.rs, crates/knope-versioning/src/versioned_file/mod.rs, crates/knope/tests/bump_version/maven/dryrun_stdout.log, crates/knope/tests/bump_version/maven/in/knope.toml, crates/knope/tests/bump_version/maven/in/pom.xml, crates/knope/tests/bump_version/maven/mod.rs, crates/knope/tests/bump_version/maven/out/pom.xml, crates/knope/tests/bump_version/mod.rs, docs/src/content/docs/reference/Config File/packages.md
Hi,
I've recently discovered knope and I really like where this project is going.
This PR adds very basic support for simple maven projects using `pom.xml`:
```xml
<project>
<modelVersion>4.0.0</modelVersion>
<groupId>com.mycompany.app</groupId>
<artifactId>my-app</artifactId>
<version>1.2.3</version>
</project>
```
Let me know what you think.
Kind regards
Michael
=> Basic pom.xml support

.changeset/add_versioning_support_for_gleamtoml_files.md, crates/knope-versioning/src/versioned_file/gleam.rs, crates/knope-versioning/src/versioned_file/mod.rs, crates/knope/tests/prepare_release/gleam_toml/dryrun_stdout.log, crates/knope/tests/prepare_release/gleam_toml/in/gleam.toml, crates/knope/tests/prepare_release/gleam_toml/in/knope.toml, crates/knope/tests/prepare_release/gleam_toml/mod.rs, crates/knope/tests/prepare_release/gleam_toml/out/gleam.toml, crates/knope/tests/prepare_release/mod.rs, docs/src/content/docs/reference/Config File/packages.md
=> Add versioning support for `gleam.toml` files

crates/knope/src/step/mod.rs, crates/knope/tests/prepare_release/go_modules/major_version_directories/dryrun_stdout.log, crates/knope/tests/prepare_release/go_modules/major_version_directories/stdout.log, crates/knope/tests/prepare_release/verbose/dryrun_stdout.log, crates/knope/tests/prepare_release/verbose/stdout.log
=> feat: Print each step before it runs when `--verbose` is set

.changeset/fix_pre_release_versioning_when_there_are_no_previous_stable_versions.md, crates/knope-versioning/src/package.rs, crates/knope-versioning/src/semver/package_versions.rs, crates/knope-versioning/src/semver/rule.rs, crates/knope/src/integrations/git.rs, crates/knope/src/step/mod.rs, crates/knope/src/step/releases/conventional_commits.rs, crates/knope/src/step/releases/mod.rs, crates/knope/src/step/releases/semver.rs, crates/knope/src/variables.rs, crates/knope/tests/bump_version/single_package/pre/from_pre/dryrun_stdout.log, crates/knope/tests/bump_version/single_package/pre/from_pre/mod.rs, crates/knope/tests/bump_version/single_package/pre/from_pre/out/Cargo.toml, crates/knope/tests/prepare_release/go_modules/major_version_directories/dryrun_stdout.log, crates/knope/tests/prepare_release/go_modules/major_version_directories/stdout.log
=> Fix pre-release versioning when there are no previous stable versions
